### PR TITLE
Use less ram

### PR DESCRIPTION
**Pull request by thesamovar**

### CODE REVIEW

**Comment by thesamovar** [comment]
@nippoo I can't merge master into this branch (it complains about multiple merge bases). I wonder if it is something to do with the fixes you made for the line ending problem. Could you try getting this branch into a state where it could be merged into master?

**Comment by nippoo** [comment]
Tell me when you're ready to merge it (presume not yet because of noopenmp bug) then I can rebase it onto master? It's just a merge conflict because of edited bits of code. Not too hard to sort out, standard git merge-tool stuff.

**Comment by thesamovar** [comment]
Really? Normally the merge tool in Eclipse works in that situation, but this time it is crashing because of multiple merge bases. I figured it must be something different.

**Comment by nippoo** [comment]
Oh maybe it is! I'll take a look. Tell me when you're ready to merge I guess, because I don't want to rewrite history while you're still working on this branch.

**Comment by thesamovar** [comment]
OK, will do.

**Comment by thesamovar** [comment]
OK this is ready to merge.

**Comment by thesamovar** [comment]
Thanks @nippoo - did it need any funky stuff done to get it merged or was it straightforward?

**Pull request merged**
